# Generated by Django 3.2.5 on 2021-09-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='@gmail.com', max_length=254)),
                ('standard', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
